### PR TITLE
Ajuste para carregar as spells dos arquivos .lua

### PR DESCRIPTION
**Pull request by curruwilla**
Detalhe para o banco de dados:

As colunas precisam ser **default null**:

- conjure_id
- conjure_count
- reagent
- item_id

image

### CODE REVIEW

**Comment by curruwilla** [comment]
As imagens, imagino que seja melhor baixar o .gif do tibia wiki com o 'name' da spell para exibir no site. 

O que acha?

**Comment by lucasgiovannibr** [comment]
Thank you very much for your cooperation, I will test and report back.
I'll leave the page the same as the global.

**Comment by lucasgiovannibr** [comment]
@curruwilla  You also deleted some boxes, if you want to disable any just go to config.php

**Comment by lucasgiovannibr** [comment]
@curruwilla To modify the tables just go to the install/includes/schema.sql file

**Comment by curruwilla** [comment]
> @curruwilla You also deleted some boxes, if you want to disable any just go to config.php

Well, I didn't even commit this and still came here for PR. I will return the files.

**Comment by curruwilla** [comment]
There are several bugs, I'm cleaning these files and indenting and fixing some, I don't think I'll be able to keep everything organized and report to PR. So I'm going to upload everything on my fork.

**Comment by curruwilla** [comment]
I removed the **config.php** because it may contain sensitive data.

So I added a **config.example.php** and a **.gitignore** to not upload the changed **config.php**.

**Pull request closed without merging**
